load('C:\Users\Makenzie\Documents\Labs\ECE 352\Lab2\Assignment Narrative\task4-1_data.mat')
y = x(1,:)
z = x(2,:)
a = abs(fft(y))
b = abs(fft(z))
figure
subplot(2,1,1)
plot(a)
title('Row 1')
xlabel('Steps (Hz) 1/N2Ds')
ylabel('Magnitude')
subplot(2,1,2)
plot(b)
title('Row 2')
xlabel('Steps (Hz) 1/N2Ds')
ylabel('Magnitude')
