load('C:\Users\Makenzie\Documents\Labs\ECE 352\Lab2\Assignment Narrative\task4-3_data.mat')
a = bitget(x, 1)
b = bitget(x, 2)
c = bitget(x, 3)
d = bitget(x, 4)
e = bitget(x, 5)
f = bitget(x, 6)
g = bitget(x, 7)
h = bitget(x, 8)